project_id = "ndgnwsayjcptaodefzlx"

[functions.add-to-woo-cart]
verify_jwt = false

[functions.analyze-skin]
verify_jwt = false

[functions.chat-advisor]
verify_jwt = false

[functions.product-advisor]
verify_jwt = false

[functions.questions-advisor]
verify_jwt = false
